[package]
name = "gameoflife"
version = "1.1.2"
edition = "2021"
authors = ["Maxwell Anderson <maxwell.anderson.public@protonmail.com>"]
license = "MIT"
description = "Conway's Game of Life running in a terminal window"
repository = "https://gitlab.com/Zaechus/gameoflife-cli"

[dependencies]
crossterm = "0.23"
ctrlc = "3.2"
rand = "0.8"
rayon = "1.5"
