[package]
name = "gameoflife"
version = "1.1.0"
authors = ["Maxwell Anderson <maxwell.anderson.public@gmail.com>"]
edition = "2021"
description = "Conway's Game of Life running in a terminal window"
repository = "https://gitlab.com/Maxgy/gameoflife-cli"
license = "MIT"

[dependencies]
crossterm = "0.23"
ctrlc = "3.2"
rand = "0.8"
rayon = "1.5"
